"""add stdin to saved_codes

Revision ID: 943da8a5ee84
Revises: 8a25077a66be
Create Date: 2026-04-21 11:55:28.600910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943da8a5ee84'
down_revision = '8a25077a66be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stdin', sa.Text(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_codes', schema=None) as batch_op:
        batch_op.drop_column('stdin')

    # ### end Alembic commands ###
